runtime: php55
api_version: 1
application: synetiqpoc
version: alpha-001

handlers:
- url: /
  script: /html/index.html
- url: /html
  static_dir: html

- url: /css
  static_dir: css

- url: /javascripts
  static_dir: javascripts

- url: /php/sendDataToDB.php
  script: /php/sendDataToDB.php

- url: /php/graph.php
  script: /php/graph.php

- url: /php/DButils.php
  script: /php/DBUtils.php
