CREATE TABLE Users(
    USERID INT NOT NULL AUTO_INCREMENT,
    USERNAME VARCHAR(100) NOT NULL,
    PRIMARY KEY( UserID)
);

CREATE TABLE Videos(
    VIDEOID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL,
    LENGTH INT NOT NULL,
    PRIMARY KEY(VIDEOID)
);


CREATE TABLE Records(
    RECORDID INT NOT NULL AUTO_INCREMENT,
    VALUE INT NOT NULL,
    SECOND INT NOT NULL,
    USERID INT NOT NULL,
    VIDEOID INT NOT NULL,
    PRIMARY KEY(RECORDID),
    FOREIGN KEY (VIDEOID) REFERENCES Videos(VIDEOID),
    FOREIGN KEY (USERID) REFERENCES Users(USERID)
);
